version: '3.8'
services:
  velociraptor:
    image: velocidex/velociraptor
    container_name: velociraptor
    ports:
      - "8000:8000"    # Velociraptor GUI
      - "8889:8889"    # gRPC للـ Agents
    volumes:
      - ./velociraptor-data:/data
    command: server --config /data/config.yaml

  arkime-viewer:
    image: ghcr.io/arkime/arkime/arkime:v5-latest
    container_name: arkime-viewer
    depends_on:
      - opensearch
    ports:
      - "8005:8005"    # واجهة Arkime Viewer
    volumes:
      - ./arkime-config:/opt/arkime/etc
      - ./arkime-pcap:/data/pcap
      - ./arkime-logs:/data/logs
    command: /opt/arkime/bin/docker.sh viewer

  arkime-capture:
    image: ghcr.io/arkime/arkime/arkime:v5-latest
    container_name: arkime-capture
    depends_on:
      - opensearch
    network_mode: "host"   
    volumes:
      - ./arkime-config:/opt/arkime/etc
      - ./arkime-pcap:/data/pcap
      - ./arkime-logs:/data/logs
    command: /opt/arkime/bin/docker.sh capture

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data