version: '3.8'

services:
  api:
    build:
      context: ../backend
    container_name: soar_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/soar_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: soar_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soar_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
