filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/**/*.json

    scan_frequency: 5s
    tail_files: false

processors:
  - add_host_metadata: ~

output.elasticsearch:
  hosts: ["https://host.docker.internal:9200"]
  username: "admin"
  password: "SecretPassword"
  ssl.verification_mode: none
  allow_older_versions: true

setup.kibana:
  host: "http://host.docker.internal:5601"