version: "3.8"

services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - SURICATA_NIC=${SURICATA_NIC}
    volumes:
      - ./suricata/config/suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./suricata/rules:/var/lib/suricata/rules:rw
      - ./suricata/logs:/var/log/suricata
    command: -i ${SURICATA_NIC}
    restart: no

volumes:
  esdata:
